from scitail.service.predictors.dgem_predictor import DgemPredictor
from scitail.service.predictors.overlap_predictor import SimpleOverlapPredictor
from scitail.service.predictors.decompatt_predictor import DecompAttPredictor
